import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import { isLoggedIn } from "@/lib/auth";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Maos Bookstore",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const loginState: boolean = isLoggedIn();

  return (
    <html lang="en">
      <body className={inter.className}>
        {/* add NAVBAR TO ALL THE CHILD */}
        <Navbar loginState={loginState} />
        {children}
      </body>
    </html>
  );
}
